language: python
python:
  - "3.7"
services:
- postgresql
install:
  - pip install -r requirements/local.txt
script:
  - "pytest"
env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.test
    - DATABASE_URL=postgres://postgres@localhost/travisdb
